# .github/workflows/ci.yml
name: jenkins

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1

      - name: Verify Go version
        run: go version

      - name: Run unit tests
        run: go test -v ./...

      - name: Build Go binary
        run: |
          go build -o main main.go
          chmod +x main

      # Optional: upload the binary as an artifact
      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          name: myapp-binary
          path: main
          retention-days: 1

      # Docker login / build / push
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build . -t myusername/myrepo:latest

      - name: Push Docker image
        run: |
          docker push myusername/myrepo:latest

      # Optional: deploy via SSH
      - name: Copy SSH key
        if: ${{ secrets.TARGET_SSH_KEY != '' }}
        run: |
          echo "${{ secrets.TARGET_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Deploy to server
        if: ${{ secrets.TARGET_SSH_KEY != '' }}
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key main laborant@your-server.example.com:/opt/myapp/main
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key laborant@your-server.example.com \
            "sudo systemctl restart myapp.service"
