# .github/workflows/ci.yml
name: Go CI & Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    # This must match the labels your self-hosted runner advertises:
    runs-on: [ self-hosted, Linux, X64 ]

    steps:
      # 1) Check out the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Install Go 1.24.1
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1

      # 3) Verify Go
      - name: Verify Go version
        run: go version

      # 4) Run unit tests
      - name: Run unit tests
        run: go test -v ./...

      # 5) Build the Go binary (produces ./main)
      - name: Build Go binary
        run: |
          go build -o main main.go
          chmod +x main

      # 6) Build Docker image (assumes Dockerfile is at repo root)
      - name: Build Docker image
        run: docker build . --tag ttl.sh/myapp:1h

      # 7) Push the image to TTL.sh
      - name: Push Docker image
        run: docker push ttl.sh/myapp:1h
